package com.llsl.viper4android.daemon

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Asserts the Kotlin codecs are byte-identical to the native ones.
 *
 * `app/src/test/resources/daemon-golden-vectors.txt` is generated by
 * `tools/DaemonGoldenVector.cpp` in the ViPERFX_RE repository
 * (`cmake --build build-host --target daemon_golden_vector && ./build-host/daemon_golden_vector`).
 * The App writes snapshots that a root daemon stores and a driver applies, so a
 * silent layout drift between the two implementations would corrupt live state.
 */
class DaemonWireCompatibilityTest {
    private val vectors: Map<String, String> by lazy {
        val stream =
            requireNotNull(
                javaClass.classLoader?.getResourceAsStream("daemon-golden-vectors.txt"),
            ) { "daemon-golden-vectors.txt is missing from test resources" }
        stream.bufferedReader().useLines { lines ->
            lines
                .filter { it.isNotBlank() }
                .map { line ->
                    val parts = line.trim().split(' ', limit = 2)
                    parts[0] to parts[1]
                }.toMap()
        }
    }

    private fun golden(name: String): String = requireNotNull(vectors[name]) { "missing vector: $name" }

    private fun ByteArray.hex(): String = joinToString("") { "%02x".format(it) }

    // Fixed inputs mirroring tools/DaemonGoldenVector.cpp.
    private val deviceKey = "speaker|builtin|internal|48000|3|pcm_16|0"
    private val bootId = 0x1122334455667788L
    private val daemonGeneration = 7L
    private val appGeneration = 5L
    private val createdAtMillis = 1700000000000L

    private fun goldenRoute() =
        AppProtocol.AppRouteReport(
            routeType = "bluetooth_a2dp",
            stableAddressOrPort = "ac:12:2f:00:11:22",
            productName = "WH-1000XM4",
            encoding = "pcm_16",
            sampleRate = 48000,
            channelMask = 3,
            outputFlags = 6,
        )

    private fun goldenRecords(): List<DaemonSnapshotCodec.RawParamRecord> {
        val bands = ByteBuffer.allocate(16).order(ByteOrder.LITTLE_ENDIAN)
        for (index in 0 until 4) {
            bands.putFloat(0.25f * (index + 1))
        }
        return listOf(
            // PARAM_EQUALIZER_ENABLE
            DaemonSnapshotCodec.RawParamRecord(param = 0x101A0, val1 = 1),
            // PARAM_MULTIBAND_COMPRESSOR_BAND_THRESHOLD
            DaemonSnapshotCodec.RawParamRecord(param = 0x10283, val1 = 2, val2 = -18, val3 = 3),
            // PARAM_EQUALIZER_BAND_LEVELS
            DaemonSnapshotCodec.RawParamRecord(param = 0x101A3, arrSize = 4, payload = bands.array()),
        )
    }

    private fun goldenSnapshot(parameters: ByteArray) =
        DaemonSnapshotCodec.Snapshot(
            deviceKey = deviceKey,
            deviceKeyHash = DaemonProtocol.hashDeviceKey(deviceKey),
            bootId = bootId,
            daemonGeneration = daemonGeneration,
            appGeneration = appGeneration,
            createdAtMillis = createdAtMillis,
            masterEnabled = true,
            globalMode = false,
            parameters = parameters,
            resources =
                listOf(
                    DaemonSnapshotCodec.ResourceReference(
                        resourceId = "kernel-a",
                        contentSha256 = "b".repeat(64),
                        size = 4096,
                        kind = 1,
                        format = 2,
                        channels = 2,
                        order = 0,
                    ),
                ),
            resourceGeneration = 11,
            graphGeneration = 12,
        )

    @Test
    fun `frame bytes match the native encoder`() {
        val payload = byteArrayOf(1, 2, 3, 4, 5, 6, 7, 8)
        val encoded =
            DaemonProtocol.encodeFrame(
                DaemonProtocol.FrameHeader(
                    messageType = 0x1234,
                    requestId = 0x0102030405060708L,
                    sequence = 42,
                ),
                payload,
            )
        assertEquals(golden("frame"), encoded.hex())
    }

    @Test
    fun `device key hash matches the native sha256`() {
        assertEquals(golden("device_key_hash"), DaemonProtocol.hashDeviceKey(deviceKey))
    }

    @Test
    fun `parameter stream bytes match the native encoder`() {
        val encoded = DaemonSnapshotCodec.encodeParameterStream(goldenRecords())
        assertEquals(golden("parameters"), encoded.hex())
    }

    @Test
    fun `parameter stream round trips through the kotlin decoder`() {
        val records = goldenRecords()
        val encoded = DaemonSnapshotCodec.encodeParameterStream(records)
        assertEquals(records, DaemonSnapshotCodec.decodeParameterStream(encoded))

        // Decoding the native bytes must produce the same records, which proves the
        // decoder is not merely symmetric with our own encoder.
        val nativeBytes = hexToBytes(golden("parameters"))
        assertEquals(records, DaemonSnapshotCodec.decodeParameterStream(nativeBytes))
    }

    @Test
    fun `snapshot bytes match the native encoder`() {
        val parameters = DaemonSnapshotCodec.encodeParameterStream(goldenRecords())
        val encoded = DaemonSnapshotCodec.encodeSnapshot(goldenSnapshot(parameters))
        assertEquals(golden("snapshot"), encoded.hex())
        // The header must be exactly the declared size, otherwise every following
        // offset shifts.
        assertEquals(
            DaemonSnapshotCodec.SNAPSHOT_HEADER_SIZE,
            encoded.size - (
                deviceKey.length + 64 + parameters.size +
                    32 + "kernel-a".length + 64
            ),
        )
    }

    @Test
    fun `snapshot crc matches the native value`() {
        val parameters = DaemonSnapshotCodec.encodeParameterStream(goldenRecords())
        val encoded = DaemonSnapshotCodec.encodeSnapshot(goldenSnapshot(parameters))
        assertEquals(golden("snapshot_crc32"), "%08x".format(DaemonProtocol.crc32(encoded)))
    }

    @Test
    fun `snapshot begin bytes match the native encoder`() {
        val parameters = DaemonSnapshotCodec.encodeParameterStream(goldenRecords())
        val snapshotBytes = DaemonSnapshotCodec.encodeSnapshot(goldenSnapshot(parameters))
        val encoded =
            DaemonSnapshotCodec.encodeSnapshotBegin(
                DaemonSnapshotCodec.SnapshotBegin(
                    appGeneration = appGeneration,
                    daemonGeneration = daemonGeneration,
                    totalSize = snapshotBytes.size,
                    crc32 = DaemonProtocol.crc32(snapshotBytes),
                    deviceKeyHash = DaemonProtocol.hashDeviceKey(deviceKey),
                ),
            )
        assertEquals(golden("begin"), encoded.hex())
        assertEquals(DaemonSnapshotCodec.SNAPSHOT_BEGIN_WIRE_SIZE, encoded.size)
    }

    @Test
    fun `snapshot chunk commit and abort bytes match the native encoder`() {
        val chunk = DaemonSnapshotCodec.encodeSnapshotChunk(256, ByteArray(8) { 0xA5.toByte() })
        assertEquals(golden("chunk"), chunk.hex())

        val commit = DaemonSnapshotCodec.encodeSnapshotCommit(appGeneration, daemonGeneration)
        assertEquals(golden("commit"), commit.hex())
        assertEquals(DaemonSnapshotCodec.SNAPSHOT_COMMIT_WIRE_SIZE, commit.size)

        val abort = DaemonSnapshotCodec.encodeSnapshotAbort(12)
        assertEquals(golden("abort"), abort.hex())
        assertEquals(DaemonSnapshotCodec.SNAPSHOT_ABORT_WIRE_SIZE, abort.size)
    }

    @Test
    fun `chunking covers the snapshot in order without gaps`() {
        val parameters = DaemonSnapshotCodec.encodeParameterStream(goldenRecords())
        val snapshotBytes = DaemonSnapshotCodec.encodeSnapshot(goldenSnapshot(parameters))
        val chunks = DaemonSnapshotCodec.chunkSnapshot(snapshotBytes, chunkSize = 64)

        var expectedOffset = 0
        val reassembled = ByteArray(snapshotBytes.size)
        for (payload in chunks) {
            val buffer = ByteBuffer.wrap(payload).order(ByteOrder.LITTLE_ENDIAN)
            val offset = buffer.int
            val length = buffer.int
            assertEquals(0L, buffer.long) // reserved
            // The driver only accepts strictly sequential offsets.
            assertEquals(expectedOffset, offset)
            assertEquals(payload.size - DaemonSnapshotCodec.SNAPSHOT_CHUNK_HEADER_SIZE, length)
            buffer.get(reassembled, offset, length)
            expectedOffset += length
        }
        assertEquals(snapshotBytes.size, expectedOffset)
        assertEquals(snapshotBytes.toList(), reassembled.toList())
    }

    @Test
    fun `app control message bytes match the native encoders`() {
        val hello = AppProtocol.encodeAppHello(AppProtocol.AppHello(appGeneration = appGeneration))
        assertEquals(golden("app_hello"), hello.hex())

        val helloAck =
            AppProtocol.encodeAppHelloAck(
                AppProtocol.AppHelloAck(
                    flags =
                        AppProtocol.FLAG_RESTORE_ENABLED or AppProtocol.FLAG_DRIVER_CONNECTED or
                            AppProtocol.FLAG_ROUTE_KNOWN,
                    daemonGeneration = daemonGeneration,
                    routeEpoch = 9,
                    routeKeyHash = DaemonProtocol.hashDeviceKey(deviceKey),
                ),
            )
        assertEquals(golden("app_hello_ack"), helloAck.hex())

        assertEquals(golden("app_route_report"), AppProtocol.encodeAppRouteReport(goldenRoute()).hex())

        val routeAck =
            AppProtocol.encodeAppRouteAck(
                AppProtocol.AppRouteAck(
                    accepted = true,
                    daemonGeneration = daemonGeneration,
                    routeEpoch = 10,
                    routeKeyHash = DaemonProtocol.hashDeviceKey(deviceKey),
                ),
            )
        assertEquals(golden("app_route_ack"), routeAck.hex())

        val applyResult =
            AppProtocol.encodeAppApplyResult(
                AppProtocol.AppApplyResult(
                    accepted = false,
                    errorCode = DaemonApplyError.STALE_GENERATION.code,
                    appGeneration = appGeneration,
                    daemonGeneration = daemonGeneration,
                    resourceGeneration = 11,
                    graphGeneration = 12,
                ),
            )
        assertEquals(golden("app_apply_result"), applyResult.hex())
    }

    @Test
    fun `app control messages decode from the native bytes`() {
        val hello = AppProtocol.decodeAppHello(hexToBytes(golden("app_hello")))
        assertEquals(appGeneration, hello.appGeneration)
        assertEquals(AppProtocol.PROTOCOL_VERSION, hello.version)

        val helloAck = AppProtocol.decodeAppHelloAck(hexToBytes(golden("app_hello_ack")))
        assertEquals(daemonGeneration, helloAck.daemonGeneration)
        assertEquals(9L, helloAck.routeEpoch)
        assertEquals(DaemonProtocol.hashDeviceKey(deviceKey), helloAck.routeKeyHash)
        assertTrue(helloAck.restoreEnabled)
        assertTrue(helloAck.driverConnected)
        assertTrue(helloAck.routeKnown)

        assertEquals(
            goldenRoute(),
            AppProtocol.decodeAppRouteReport(hexToBytes(golden("app_route_report"))),
        )

        val routeAck = AppProtocol.decodeAppRouteAck(hexToBytes(golden("app_route_ack")))
        assertTrue(routeAck.accepted)
        assertEquals(daemonGeneration, routeAck.daemonGeneration)
        assertEquals(10L, routeAck.routeEpoch)
        assertEquals(DaemonProtocol.hashDeviceKey(deviceKey), routeAck.routeKeyHash)

        val applyResult = AppProtocol.decodeAppApplyResult(hexToBytes(golden("app_apply_result")))
        assertFalse(applyResult.accepted)
        assertEquals(DaemonApplyError.STALE_GENERATION.code, applyResult.errorCode)
        assertEquals(appGeneration, applyResult.appGeneration)
        assertEquals(daemonGeneration, applyResult.daemonGeneration)
        assertEquals(11L, applyResult.resourceGeneration)
        assertEquals(12L, applyResult.graphGeneration)
    }

    @Test
    fun `golden vectors are all present`() {
        // A missing fixture would silently skip a compatibility assertion.
        for (name in listOf(
            "frame",
            "parameters",
            "snapshot",
            "device_key_hash",
            "snapshot_crc32",
            "begin",
            "chunk",
            "commit",
            "abort",
            "app_hello",
            "app_hello_ack",
            "app_route_report",
            "app_route_ack",
            "app_apply_result",
        )) {
            assertNotNull("missing vector: $name", vectors[name])
        }
    }

    private fun hexToBytes(hex: String): ByteArray =
        ByteArray(hex.length / 2) { index ->
            hex.substring(index * 2, index * 2 + 2).toInt(16).toByte()
        }
}
